//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FRS.Repository.BaseRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Users = new HashSet<User>();
        }
    
        public long EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string Designation { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
