//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cares.WebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApiResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApiResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cares.WebApp.Resources.ApiResource", typeof(ApiResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAdditionalDriverCharge.
        /// </summary>
        public static string GetAdditionalDriverCharge {
            get {
                return ResourceManager.GetString("GetAdditionalDriverCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAvailableChauffersRates.
        /// </summary>
        public static string GetAvailableChauffersRates {
            get {
                return ResourceManager.GetString("GetAvailableChauffersRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAvailableInsuranceRates.
        /// </summary>
        public static string GetAvailableInsuranceRates {
            get {
                return ResourceManager.GetString("GetAvailableInsuranceRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetAvailableHireGroups.
        /// </summary>
        public static string GetHireGroup {
            get {
                return ResourceManager.GetString("GetHireGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetOperationWorkplace.
        /// </summary>
        public static string GetOperationWorkplace {
            get {
                return ResourceManager.GetString("GetOperationWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string GetServices {
            get {
                return ResourceManager.GetString("GetServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegisterUser.
        /// </summary>
        public static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetBookingMain.
        /// </summary>
        public static string SetBookingMain {
            get {
                return ResourceManager.GetString("SetBookingMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost/WebApi/Api/.
        /// </summary>
        public static string WebApiBaseAddress {
            get {
                return ResourceManager.GetString("WebApiBaseAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QWEasd123.
        /// </summary>
        public static string WebApiPassword {
            get {
                return ResourceManager.GetString("WebApiPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to innoist.
        /// </summary>
        public static string WebApiUserName {
            get {
                return ResourceManager.GetString("WebApiUserName", resourceCulture);
            }
        }
    }
}
